version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "${GATEWAY_PORT:-5001}:5001"
    env_file:
      - .env
    depends_on:
      - service1
      - service2
    volumes:
      - shared-data:/app/data
    # (Optional) You could add a healthcheck for the gateway itself here

  service1:
    build: ./services/service1
    container_name: service1
    env_file:
      - .env
    volumes:
      - shared-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVICE1_PORT}/process"]
      interval: 10s
      timeout: 5s
      retries: 5

  service2:
    build: ./services/service2
    container_name: service2
    env_file:
      - .env
    volumes:
      - shared-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVICE2_PORT}/process"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  shared-data: