version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "${GATEWAY_PORT:-5001}:5001"
    env_file:
      - .env
    depends_on:
      - service1
      - service2
    volumes:
      - ./shared-data:/app/data  # Shared volume for persistent storage
      - ./config.py:/app/config.py 

  service1:
    build: ./services/service1
    container_name: service1
    env_file:
      - .env
    volumes:
      - ./shared-data:/app/data
      - ./config.py:/app/config.py  

  service2:
    build: ./services/service2
    container_name: service2
    env_file:
      - .env
    volumes:
      - ./shared-data:/app/data
      - ./config.py:/app/config.py  

  service3:
    build: ./services/service3
    container_name: service3
    env_file:
      - .env
    volumes:
      - ./shared-data:/app/data  # <-- Shared directory for images and logs
      - ./config.py:/app/config.py  

volumes:
  shared-data:
    driver: local