version: '3.8'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5001:5001"  # Host 5001 -> Container 5001
    environment:
      - DOCKER_MODE=true
      - GATEWAY_PORT=5001
    depends_on:
      - service1
      - service2

  service1:
    build: ./services/service1
    container_name: service1
    environment:
      - SERVICE_NAME=service1
      - PORT=5002

  service2:
    build: ./services/service2
    container_name: service2
    environment:
      - SERVICE_NAME=service2
      - PORT=5003